config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :highlights, except: [:show] do
    put :sort, on: :collection
  end
  get 'highlights/:id', to: 'highlights#show', as: 'highlight_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable' 

  root to: 'pages#home'
end

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
    <div class="inner">
        <h3 class="masthead-brand">Kostas Ntallas</h3>
            <nav class="nav nav-masthead justify-content-center app-nav">
                <%= nav_helper 'nav-link', 'span' %>
                <%= login_helper 'nav-link' %>
            </nav>
    </div>
</header>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
    <p>
        <%= copyright_generator %>
    </p>
    <p>
        <a href="#">Back to top</a>
    </p>
</footer>

app/views/shared/_blog_header.html.erb
<div class="jumbotron p-4 p-md-5 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
        <h1 class="display-4 font-italic">Title of a longer featured blog post</h1>
        <p class="lead my-3">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what’s most interesting in this post’s contents.</p>
        <p class="lead mb-0"><a href="#" class="text-white font-weight-bold">Continue reading...</a></p>
        <span>
            <%= link_to 'New Blog', new_blog_path if logged_in?(:site_admin) %>
        </span>
        <span>
            <%= link_to "Topics", topics_path %>
        </span>
    </div>
</div>

app/views/shared/_blog_nav.html.erb
<div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between blog-nav">
        <%= nav_helper 'text-muted', 'span' %>
        <%= login_helper 'p-2 text-muted' %>
    </nav>
</div>

app/views/shared/_footer.html.erb
<footer class="mastfoot mt-auto">
    <div class="inner">
        <p class="app-footer"><%= copyright_generator %></p>
    </div>
</footer>

app/views/shared/_highlights_footer.html.erb
<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <%= link_to "View all Highlights",  highlights_path %> /
            <a href="#">Back to top</a>
        </p>
        <p><%= copyright_generator %></p>
    </div>
</footer>

app/views/shared/_highlights_header.html.erb
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Album example</h1>
        <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
        <p>
            <%= link_to 'Find Out More About Me', about_path, class: 'btn btn-primary my-2' %>
            <%= link_to 'My Blog', blogs_path, class: 'btn btn-secondary my-2' %>
        </p>
    </div>
</section>

app/views/shared/_highlights_nav.html.erb
<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
                <h4 class="text-white">About</h4>
                <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
                <h4 class="text-white">Explore</h4>
                <ul class="list-unstyled">
                    <%= nav_helper 'text-white', 'li' %>
                    <li><%= login_helper 'text-white' %></li>
                </ul>
            </div>
            </div>
        </div>
        </div>
        <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container d-flex justify-content-between">
            <a href="#" class="navbar-brand d-flex align-items-center">
            <strong>Kostas Ntallas</strong>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

app/views/shared/_sidebar.html.erb
<aside class="col-md-4 blog-sidebar">
    <div class="p-4 mb-3 bg-light rounded">
        <h4 class="font-italic">About</h4>
        <p class="mb-0">Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
    </div>

    <%= source_helper('alert alert-info') %> 

    <div class="p-4">
        <h4>Topics</h4>
        <% @sidebar_topics.each do |topic| %>
            <p><%= link_to topic.title, topic_path(topic) %></p>
        <% end %>
    </div>
    <div class="p-4">
        <h4 class="font-italic">Elsewhere</h4>
        <ol class="list-unstyled social-links">
            <li><a href="#"><%= fa_icon "github" %></a></li>
            <li><a href="#"><%= fa_icon "facebook" %></a></li>
            <li><a href="#"><%= fa_icon "instagram" %></a></li>
            <li><a href="#"><%= fa_icon "twitter" %></a></li>
        </ol>
    </div>
</aside>