config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :highlights, except: [:show] do
    put :sort, on: :collection
  end
  get 'highlights/:id', to: 'highlights#show', as: 'highlight_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable' 

  root to: 'pages#home'
end

app/models/highlight.rb
class Highlight < ApplicationRecord
    has_many :technologies
    accepts_nested_attributes_for :technologies,
                                  allow_destroy: true,
                                  reject_if: lambda { |attrs| attrs['name'].blank? }

    validates_presence_of :title, :body
    
    mount_uploader :thumb_image, HighlightUploader
    mount_uploader :main_image, HighlightUploader

    def self.reactjs
        where(subtitle: 'React JS')
    end

    def self.by_position
        order("position ASC")
    end

    scope :ruby_on_rails_highlight_items, -> { where(subtitle: 'Ruby on Rails') }
end

app/controllers/highlights_controller.rb
class HighlightsController < ApplicationController
    before_action :set_highlight, only: [:edit, :update, :show, :destroy] 
    access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all
    layout "highlight"

    def index
        @highlights = Highlight.by_position
    end

    def sort
      params[:order].each do |key, value|
        Highlight.find(value[:id]).update(position: value[:position])
      end
      render nothing: true
    end

    def new
        @highlight = Highlight.new
    end

    def create
        @highlight = Highlight.new(highlight_params)
    
        respond_to do |format|
          if @highlight.save
            format.html { redirect_to highlights_path, notice: 'Highlight was successfully created.' }
          else
            format.html { render :new }
          end
        end
    end

    def edit
    end

    def update
      respond_to do |format|
        if @highlight.update(highlight_params)
          format.html { redirect_to highlights_path, notice: 'Portfolio item was successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    end

    def show
    end

    def destroy
      @highlight.destroy

      respond_to do |format|
        format.html { redirect_to highlights_url, notice: 'Portfolio item was successfully destroyed.' }
      end

    end

    private

    def highlight_params
      params.require(:highlight).permit(:title,
                                        :subtitle, 
                                        :body,
                                        :main_image,
                                        :thumb_image, 
                                        technologies_attributes: [:id, :name, :_destroy])
    end

    def set_highlight
      @highlight = Highlight.find(params[:id])
    end

end

app/helpers/highlights_helper.rb
module HighlightsHelper
    def image_generator(height:, width:)
        "https://via.placeholder.com/#{height}x#{width}"
    end
    def highlight_img img, type
        if img
            img
        elsif type == 'thumb'
            image_generator(height: '350', width: '200')
        elsif type == 'main'
            image_generator(height: '600', width: '400')
        end
    end    
end

app/views/highlights/_form.html.erb
<%= form_for(@highlight) do |form| %>
  <% if @highlight.errors.any? %>
  <% @highlight.errors.full_messages.each do |error| %>
    <%= alert_generator error %>
  <% end %>
<% end %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :subtitle %>
        <%= form.text_field :subtitle, class: 'form-control' %>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload a main image file<%= form.file_field :main_image, style: 'display:none' %>
        </label>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload a thumb image file<%= form.file_field :thumb_image, style: 'display:none' %>
        </label>
      </div>

    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :body %>
        <%= form.text_area :body, class: 'form-control', rows: 13 %>
      </div>
    </div>

    <hr> 

    <div class="col-md-12">
      <h2>Technologies Used:</h2>
      <div>
        <%= form.fields_for :technologies do |technology_form| %>
          <%= render 'technology_fields', f: technology_form %>
        <% end %>

        <div>
          <%= link_to_add_association 'Add Technolog', f, :technologies %>
        </div>
      </div>

      <div class="form-group">
        <%= form.submit 'Save Highlight Item', class: 'btn btn-primary btn-block' %>
      </div>
    </div>
  </div> 
<% end %>

app/views/highlights/_highlight.html.erb
<div class="col-md-4">
<div class="card mb-4 shadow-sm" data-id="<%= highlight.id %>">
<%= image_tag highlight_img(highlight.thumb_image.url, 'thumb'), width: '100%' %>
  <div class="card-body">
    <p class="card-text">
        <span><%= link_to highlight.title, highlight_path(highlight) %></span>
        <%= highlight.subtitle %>
    </p>
  </div>
</div>
</div>

app/views/highlights/_technology_fields.html.erb
<div class="form-group nested-fields">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    <%= link_to_remove_association 'Remove Technology', f %>
</div>

app/views/highlights/edit.html.erb
<div class="container highlight-container">
    <h1>Edit this Portfolio Item</h1>

    <%= render 'form', highlight: @highlight%>
</div>

app/views/highlights/index.html.erb
<div class="album py-5 bg-light">
    <div class="container">
        <%= source_helper('alert alert-warning') %>
        <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
            <%= render partial: 'highlight', collection: @highlights %>
        </div>
    </div>
</div>

app/views/highlights/new.html.erb
<div class="container highlight-container">
    <h1>Create a New Portfolio Item</h1>

    <%= render 'form', highlight: @highlight%>
</div>

app/views/highlights/show.html.erb
<div class="container highlight-container">
    <div class="row">
        <div class="col-md-7">
            <%= image_tag highlight_img(@highlight.main_image.url, 'main') %>
        </div>
        <div class="col-md-5">
            <h1><%= @highlight.title %></h1>
            <hr>
            <em><%= @highlight.subtitle %></em>
            <p><%= @highlight.body %></p>
            <hr>
            <h3>Technologies Used:</h3>
            <% @highlight.technologies.each do |t| %>
                <p><%= t.name %></p>
            <% end %>

            <% if logged_in?(:site_admin)%>
                <%= link_to "Edit Item", edit_highlight_path(@highlight), class: 'btn btn-warning' %>
            <% end %>
        </div>
    </div>
</div>